// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwdrstwmxzlejhfumueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3ZHJzdHdteHpsZWpoZnVtdWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODY0NzQsImV4cCI6MjA2MTQ2MjQ3NH0.EMIVJ933w1CpwrRuYbjvv2wzLZRrmFZiD-nqHNN6U-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);